[package]
name = "nyanpasu-core-manager"
version = "0.1.1"
edition.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
doc = false
name = "nyanpasu-fake-core"
path = "tests/helpers/fake_core.rs"

[dependencies]
camino = { version = "1.1", features = ["serde1"] }
chrono.workspace = true
clash-api = { path = "../clash-api" }
enumset = "1"
parking_lot = "0.12"
nyanpasu-core-metadata = { path = "../nyanpasu-core-metadata" }
nyanpasu-utils = { path = "../nyanpasu-utils", features = ["process"] }
serde.workspace = true
serde_json = "1"
serde_yaml_ng = "0.10"
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
zerocopy = { version = "0.8", features = ["derive", "simd"] }

[features]
default = []
test-hooks = []

[dev-dependencies]
tempfile = "3"

[target.'cfg(windows)'.dependencies]
windows.workspace = true
